#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 2 "..\..\Areas\CMS\Views\Info\_Form_Content.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Info/_Form_Content.cshtml")]
    public partial class _Areas_CMS_Views_Info__Form_Content_cshtml : System.Web.Mvc.WebViewPage<NewLife.CMX.IInfo>
    {
        public _Areas_CMS_Views_Info__Form_Content_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\CMS\Views\Info\_Form_Content.cshtml"
  
    var inf = Model as IInfo;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 91), Tuple.Create("\"", 132)
, Tuple.Create(Tuple.Create("", 97), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.config.js")
, 97), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 152), Tuple.Create("\"", 194)
, Tuple.Create(Tuple.Create("", 158), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.all.min.js")
, 158), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 214), Tuple.Create("\"", 257)
, Tuple.Create(Tuple.Create("", 220), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/lang/zh-cn/zh-cn.js")
, 220), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" id=\"ContentText\"");

WriteLiteral(" name=\"ContentText\"");

WriteLiteral(" type=\"text/plain\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Areas\CMS\Views\Info\_Form_Content.cshtml"
Write(Html.Raw(inf.ContentText));

            
            #line default
            #line hidden
WriteLiteral("\r\n</script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    //实例化编辑器
    //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例
    var _width = $(document.body).width() * 0.75;//浏览器当前窗口文档body的高度
    var ue = UE.getEditor('ContentText', {
        initialFrameWidth: _width,
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
