#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 4 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
    using NewLife.CMX.Web;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Info/_Form_Title.cshtml")]
    public partial class _Areas_CMS_Views_Info__Form_Title_cshtml : System.Web.Mvc.WebViewPage<NewLife.CMX.IInfo>
    {
        public _Areas_CMS_Views_Info__Form_Title_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var fields = ViewBag.Fields as List<FieldItem>;
    var entity = Model as IEntity;
    var isNew = entity.IsNullKey;

    var inf = Model as IInfo;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group col-xs-12\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" class=\"control-label col-xs-2 col-md-2\"");

WriteLiteral(">标题</label>\r\n    <div");

WriteLiteral(" class=\"col-xs-10 col-sm-8 col-md-9 col-lg-6\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
   Write(Html.ForEditor("Title", inf.Title, typeof(String)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    &nbsp;\r\n");

            
            #line 20 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
     if (!isNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 638), Tuple.Create("\"", 662)
            
            #line 23 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
, Tuple.Create(Tuple.Create("", 645), Tuple.Create<System.Object, System.Int32>(this.GetUrl(inf)
            
            #line default
            #line hidden
, 645), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                预览\r\n            </a>\r\n        </div>\r\n");

            
            #line 27 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div");

WriteLiteral(" class=\"form-group col-sm-12 col-md-6\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" class=\"control-label col-sm-2 col-md-4\"");

WriteLiteral(">分类</label>\r\n    <div");

WriteLiteral(" class=\"col-sm-4 col-md-4\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
          
            var data = new SelectList(Category.Root.AllChilds, "ID", "TreeNodeText", inf.CategoryID);
        
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 35 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
   Write(Html.DropDownList("CategoryID", data, new { @class = "multiselect" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-sm-4 col-md-4\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">访问量</label>\r\n        <span>");

            
            #line 39 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
         Write(inf.Views);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">版本</label>\r\n        <span>");

            
            #line 41 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
         Write(inf.Version);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group col-sm-12 col-md-6\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" class=\"control-label col-xs-2 col-md-2\"");

WriteLiteral(">编码</label>\r\n    <div");

WriteLiteral(" class=\"col-xs-7 col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 47 "..\..\Areas\CMS\Views\Info\_Form_Title.cshtml"
   Write(Html.ForEditor("Code", inf.Code, typeof(String)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
