#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Shared/_Layout_Nav.cshtml")]
    public partial class _Areas_CMS_Views_Shared__Layout_Nav_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_CMS_Views_Shared__Layout_Nav_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
  
    var chn = ViewBag.Channel as Channel;
    var cat = ViewBag.Category as IEntityCategory;

            
            #line default
            #line hidden
WriteLiteral("\r\n<i");

WriteLiteral(" class=\"ace-icon fa fa-home home-icon\"");

WriteLiteral("></i>\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 172), Tuple.Create("\"", 244)
            
            #line 7 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 179), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { channel = chn.ID, category = cat.ID })
            
            #line default
            #line hidden
, 179), false)
);

WriteLiteral(" class=\"h4\"");

WriteLiteral("><strong>");

            
            #line 7 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
                                                                                          Write(chn.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong></a>\r\n");

            
            #line 8 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
 if (cat != null)
{
    foreach (IEntityCategory item in cat.AllParents)
    {
        if (item.ID != 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("&nbsp;/&nbsp;");

WriteLiteral("\r\n");

WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 464), Tuple.Create("\"", 537)
            
            #line 15 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 471), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { channel = chn.ID, category = item.ID })
            
            #line default
            #line hidden
, 471), false)
);

WriteLiteral(" class=\"h4\"");

WriteLiteral(">");

            
            #line 15 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
                                                                                               Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 16 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
        }
    }
}

            
            #line default
            #line hidden
WriteLiteral("&nbsp;/&nbsp;<a");

WriteAttribute("href", Tuple.Create(" href=\"", 602), Tuple.Create("\"", 674)
            
            #line 19 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
, Tuple.Create(Tuple.Create("", 609), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { channel = chn.ID, category = cat.ID })
            
            #line default
            #line hidden
, 609), false)
);

WriteLiteral(" class=\"h4\"");

WriteLiteral("><strong>");

            
            #line 19 "..\..\Areas\CMS\Views\Shared\_Layout_Nav.cshtml"
                                                                                                       Write(cat.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong></a>");

        }
    }
}
#pragma warning restore 1591
