#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Shared/_UserTime.cshtml")]
    public partial class _Areas_CMS_Views_Shared__UserTime_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_CMS_Views_Shared__UserTime_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
  
    var entity = Model as IEntity;
    var fact = EntityFactory.CreateOperate(entity.GetType());

    var user = Model as IUserInfo;
    var time = Model as ITimeInfo;
    var cip = fact.Table.FindByName("CreateIP");
    var uip = fact.Table.FindByName("UpdateIP");

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
 if (user != null || time != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">创建</label>\r\n        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
             if (user != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteLiteral(">");

            
            #line 18 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
                                      Write(user.CreateUserName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 19 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 20 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
             if (time != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 22 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
                                      Write(time.CreateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 23 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 24 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
             if (!Object.Equals(cip, null))
            {
                var ip = entity[cip.Name] + "";

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteAttribute("title", Tuple.Create(" title=\"", 890), Tuple.Create("\"", 901)
            
            #line 27 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
, Tuple.Create(Tuple.Create("", 898), Tuple.Create<System.Object, System.Int32>(ip
            
            #line default
            #line hidden
, 898), false)
);

WriteLiteral(">");

            
            #line 27 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
                                                  Write(ip.IPToAddress());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 28 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <label");

WriteLiteral(" class=\"control-label col-md-1\"");

WriteLiteral(">更新</label>\r\n        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
             if (user != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteLiteral(">");

            
            #line 34 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
                                      Write(user.UpdateUserName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 35 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 36 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
             if (time != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 38 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
                                      Write(time.UpdateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 39 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 40 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
             if (!Object.Equals(uip, null))
            {
                var ip = entity[uip.Name] + "";

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-primary\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1480), Tuple.Create("\"", 1491)
            
            #line 43 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
, Tuple.Create(Tuple.Create("", 1488), Tuple.Create<System.Object, System.Int32>(ip
            
            #line default
            #line hidden
, 1488), false)
);

WriteLiteral(">");

            
            #line 43 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
                                                  Write(ip.IPToAddress());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 44 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("      </div>\r\n    </div>\r\n");

            
            #line 47 "..\..\Areas\CMS\Views\Shared\_UserTime.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
