#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 2 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 5 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 3 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Shared/Form.cshtml")]
    public partial class _Areas_CMS_Views_Shared_Form_cshtml : System.Web.Mvc.WebViewPage<NewLife.CMX.IInfo>
    {
        public _Areas_CMS_Views_Shared_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
  
    Layout = "~/Views/Shared/_Ace_Layout.cshtml";
    var fact = ViewBag.Factory as IEntityOperate;
    var fields = ViewBag.Fields as List<FieldItem>;
    var entity = Model as IEntity;
    var isNew = entity.IsNullKey;
    var inf = Model as IInfo;

    // 创建更新等信息统一放在尾部
    var names = new String[] {
        "CreateUserID", "CreateUserName", "CreateTime",
        "UpdateUserID", "UpdateUserName", "UpdateTime",
        "Remark" };
    fields = fields.Where(e => !e.Name.EqualIgnoreCase(names)).ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
         if (ViewBag.StatusMessage != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"alert alert-success alert-dismissible text-center\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                <strong>");

            
            #line 27 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n            </div>\r\n");

            
            #line 29 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 30 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
         using (Html.BeginForm((isNew ? "Add" : "Edit"), null, new { id = entity[fact.Unique.Name] }))
        {
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                                     
            foreach (var item in fields)
            {
                if (!item.PrimaryKey)
                {
                    if (item.Name == "ContentText")
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1503), Tuple.Create("\"", 1544)
, Tuple.Create(Tuple.Create("", 1509), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.config.js")
, 1509), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("                        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1588), Tuple.Create("\"", 1630)
, Tuple.Create(Tuple.Create("", 1594), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.all.min.js")
, 1594), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("                        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1674), Tuple.Create("\"", 1717)
, Tuple.Create(Tuple.Create("", 1680), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/lang/zh-cn/zh-cn.js")
, 1680), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("                        <script");

WriteLiteral(" id=\"ContentText\"");

WriteLiteral(" name=\"ContentText\"");

WriteLiteral(" type=\"text/plain\"");

WriteLiteral(" style=\"width:1024px;height:500px;\"");

WriteLiteral(">\r\n                        </script>\r\n");

WriteLiteral("                        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                            //实例化编辑器\r\n                            //建议使用工厂方法ge" +
"tEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor(\'editor\')就能拿到相关的实例\r\n          " +
"                  var ue = UE.getEditor(\'ContentText\');\r\n                       " +
" </script>\r\n");

            
            #line 50 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 54 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                       Write(Html.Partial("_Form_Item", new Pair(entity, item)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");

            
            #line 56 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                    }

                }
            }
            if (entity is IUserInfo || entity is ITimeInfo)
            {
                
            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
           Write(Html.Partial("_UserTime", entity as IEntity));

            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                                                             
            }
            var remark = fact.Table.FindByName("Remark") as FieldItem;
            if (remark != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">");

            
            #line 68 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                                                     Write(remark.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                    <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 70 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                   Write(Html.ForString(remark.Name, (String)entity[remark.Name], -1));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 71 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                   Write(Html.ForDescription(remark));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

            
            #line 74 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
            }
            
            
            #line default
            #line hidden
            
            #line 75 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
       Write(Html.Partial("_Form_Action", isNew));

            
            #line default
            #line hidden
            
            #line 75 "..\..\Areas\CMS\Views\Shared\Form.cshtml"
                                                
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
