#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.CMX;
    using NewLife.CMX.Web;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Text/Category.cshtml")]
    public partial class _Views_Text_Category_cshtml : System.Web.Mvc.WebViewPage<NewLife.CMX.ICategory>
    {
        public _Views_Text_Category_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Text\Category.cshtml"
  
    var infs = ViewBag.Infos as IList<IInfo>;
    var Pager = ViewBag.Pager as Pager;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"min-height: 600px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\Text\Category.cshtml"
   Write(Html.Partial("_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <h2");

WriteLiteral(" class=\"tith2\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Text\Category.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h2>\r\n");

            
            #line 13 "..\..\Views\Text\Category.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Text\Category.cshtml"
      
        var childs = Model.Childs;
        if (childs.Count > 0)
        {
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Text\Category.cshtml"
       Write(Html.Partial("_Category_Childs", Model));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Text\Category.cshtml"
                                                    
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <ul");

WriteLiteral(" class=\"list_news_dl fixed\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Text\Category.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Text\Category.cshtml"
                 foreach (var item in infs)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 636), Tuple.Create("\"", 661)
            
            #line 25 "..\..\Views\Text\Category.cshtml"
, Tuple.Create(Tuple.Create("", 643), Tuple.Create<System.Object, System.Int32>(this.GetUrl(item)
            
            #line default
            #line hidden
, 643), false)
);

WriteLiteral(">\r\n                            <i></i>");

            
            #line 26 "..\..\Views\Text\Category.cshtml"
                              Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </li>\r\n");

            
            #line 29 "..\..\Views\Text\Category.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

            
            #line 31 "..\..\Views\Text\Category.cshtml"
            
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Text\Category.cshtml"
       Write(Html.Partial("_Category_Pager", Model));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Text\Category.cshtml"
                                                   
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
