#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 2 "..\..\Areas\CMS\Views\Article\Form.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 5 "..\..\Areas\CMS\Views\Article\Form.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\CMS\Views\Article\Form.cshtml"
    using NewLife.CMX.Web;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 3 "..\..\Areas\CMS\Views\Article\Form.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\CMS\Views\Article\Form.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Article/Form.cshtml")]
    public partial class _Areas_CMS_Views_Article_Form_cshtml : System.Web.Mvc.WebViewPage<NewLife.CMX.IInfo>
    {
        public _Areas_CMS_Views_Article_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Areas\CMS\Views\Article\Form.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var entity = Model as IEntity;
    var isNew = entity.IsNullKey;
    var inf = Model as IInfo;
    var article = inf.Ext as IArticle;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Areas\CMS\Views\Article\Form.cshtml"
   Write(Html.Partial("_Form_Header", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 17 "..\..\Areas\CMS\Views\Article\Form.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\CMS\Views\Article\Form.cshtml"
         using (Html.BeginForm((isNew ? "Add" : "Edit"), null, new { id = Model[fact.Unique.Name] }))
        {
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\CMS\Views\Article\Form.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\CMS\Views\Article\Form.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                     
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\CMS\Views\Article\Form.cshtml"
       Write(Html.Partial("_Form_Title", entity));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                                

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-sm-2\"");

WriteLiteral(">来源</label>\r\n                <div");

WriteLiteral(" class=\"col-sm-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.ForDropDownList(Article._.SourceID, Source.FindAllVisible().Cast<IEntity>().ToList(), null, false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">名称</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 30 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                   Write(Html.ForEditor(Article._.SourceName, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">地址</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                   Write(Html.ForEditor(Article._.SourceUrl, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-sm-2 col-md-2\"");

WriteLiteral(">内容</label>\r\n                <div");

WriteLiteral(" class=\"col-sm-10 col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 43 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.Partial("_Form_Content", entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">摘要</label>\r\n                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.TextArea("Summary", inf.Summary, 5, 100, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

            
            #line 53 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                
            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                   var item = Article._.Top;
            
            #line default
            #line hidden
WriteLiteral("\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">");

            
            #line 54 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                                 Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 56 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.ForEditor(item, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 58 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                
            
            #line default
            #line hidden
            
            #line 58 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                   item = Article._.Recommend;
            
            #line default
            #line hidden
WriteLiteral("\r\n                <label");

WriteLiteral(" class=\"control-label col-md-1\"");

WriteLiteral(">");

            
            #line 59 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                                 Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.ForEditor(item, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 63 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                
            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                   item = Article._.Hot;
            
            #line default
            #line hidden
WriteLiteral("\r\n                <label");

WriteLiteral(" class=\"control-label col-md-1\"");

WriteLiteral(">");

            
            #line 64 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                                 Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 66 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.ForEditor(item, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                ");

WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">封面</label>\r\n                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 77 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.ForEditor(Article._.Cover, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">发布时间</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 84 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                   Write(Html.ForEditor("PublishTime", inf.PublishTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 88 "..\..\Areas\CMS\Views\Article\Form.cshtml"
            
            
            #line default
            #line hidden
            
            #line 88 "..\..\Areas\CMS\Views\Article\Form.cshtml"
       Write(Html.Partial("_Form_Footer", entity));

            
            #line default
            #line hidden
            
            #line 88 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                                 
                    
            
            #line default
            #line hidden
            
            #line 89 "..\..\Areas\CMS\Views\Article\Form.cshtml"
               Write(Html.Partial("_Form_Action", entity));

            
            #line default
            #line hidden
            
            #line 89 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                                                         
                    }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(\"#");

            
            #line 94 "..\..\Areas\CMS\Views\Article\Form.cshtml"
   Write(Article._.SourceID);

            
            #line default
            #line hidden
WriteLiteral("\").change(\r\n           function () {\r\n               var v = $(\"#");

            
            #line 96 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                      Write(Article._.SourceID);

            
            #line default
            #line hidden
WriteLiteral(@""").val();
               $.ajax({
                   type: ""Post"",//使用get方法访问后台
                   dataType: ""json"",//返回json格式的数据
                   url: '/CMS/Source/Get/' + v,//要访问的后台地址
                   success: function (msg) {//msg为返回的数据，在这里做数据绑定
                       $(""#");

            
            #line 102 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                      Write(Article._.SourceName);

            
            #line default
            #line hidden
WriteLiteral("\").attr(\"value\", msg.Name);\r\n                       $(\"#");

            
            #line 103 "..\..\Areas\CMS\Views\Article\Form.cshtml"
                      Write(Article._.SourceUrl);

            
            #line default
            #line hidden
WriteLiteral("\").attr(\"value\", msg.Url);\r\n                   }\r\n               });\r\n           " +
"});\r\n</script>");

        }
    }
}
#pragma warning restore 1591
