#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 1 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 3 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    using NewLife.Cube;
    
    #line 2 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    using NewLife.Model;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/_Left.cshtml")]
    public partial class _Areas_Admin_Views_Index__Left_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index__Left_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
  
    var user = ManageProvider.User;

    var fact = ObjectContainer.Current.Resolve<IMenuFactory>();

    var Menus = fact.Root.Childs;
    if (user != null && user.Role != null)
    {
        Menus = fact.GetMySubMenus(fact.Root.ID);
    }

    // 如果顶级只有一层，并且至少有三级目录，则提升一级
    if (Menus.Count == 1 && Menus[0].Childs.All(m => m.Childs.Count > 0)) { Menus = Menus[0].Childs; }

    String[] icos = new String[] { "fa-tachometer", "fa-desktop", "fa-list", "fa-pencil-square-o", "fa-list-alt", "fa-calendar", "fa-picture-o", "fa-tag", "fa-file-o" };
    Int32 _idx = 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n<ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
     foreach (IMenu menu in Menus.Where(m => m.Visible))
    {
        var childs = fact.GetMySubMenus(menu.ID).Where(m => m.Visible);
        if (_idx >= icos.Length) { _idx = 0; }

            
            #line default
            #line hidden
WriteLiteral("        <li ");

            
            #line 26 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
       Write(Html.Raw(menu == Menus[0] ? "class=\"active open\"" : ""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(">\r\n                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 1009), Tuple.Create("\"", 1043)
, Tuple.Create(Tuple.Create("", 1017), Tuple.Create("menu-icon", 1017), true)
, Tuple.Create(Tuple.Create(" ", 1026), Tuple.Create("fa", 1027), true)
            
            #line 28 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create(" ", 1029), Tuple.Create<System.Object, System.Int32>(icos[_idx++]
            
            #line default
            #line hidden
, 1030), false)
);

WriteLiteral("></i>\r\n                <span");

WriteLiteral(" class=\"menu-text\"");

WriteLiteral(">");

            
            #line 29 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                   Write(menu.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n                <b");

WriteLiteral(" class=\"arrow fa fa-angle-down\"");

WriteLiteral("></b>\r\n            </a>\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
             if (childs.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n");

            
            #line 36 "..\..\Areas\Admin\Views\Index\_Left.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\r\n");

            
            #line 38 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                     foreach (IMenu menu2 in childs)
                    {
                        
            
            #line default
            #line hidden
            
            #line 40 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                   Write(Html.Partial("_Left_Item", menu2));

            
            #line default
            #line hidden
            
            #line 40 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                                          ;
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul>\r\n");

            
            #line 43 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </li>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n");

            
            #line 47 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
     foreach (var mod in ModelX.GetAll())
    {
        // 判断是否有权访问该频道
        var res = "CMS\\" + mod.Name;
        //if (!user.Has(res) && !user.Has(res + "Category")) { continue; }
        //if (!user.Has(res)) { continue; }
        if (_idx >= icos.Length) { _idx = 0; }

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(">\r\n                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 1924), Tuple.Create("\"", 1958)
, Tuple.Create(Tuple.Create("", 1932), Tuple.Create("menu-icon", 1932), true)
, Tuple.Create(Tuple.Create(" ", 1941), Tuple.Create("fa", 1942), true)
            
            #line 56 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create(" ", 1944), Tuple.Create<System.Object, System.Int32>(icos[_idx++]
            
            #line default
            #line hidden
, 1945), false)
);

WriteLiteral("></i>\r\n                <span");

WriteLiteral(" class=\"menu-text\"");

WriteLiteral(">");

            
            #line 57 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                   Write(mod.ToString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n                <b");

WriteLiteral(" class=\"arrow fa fa-angle-down\"");

WriteLiteral("></b>\r\n            </a>\r\n\r\n            <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n\r\n            <ul");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2223), Tuple.Create("\"", 2252)
, Tuple.Create(Tuple.Create("", 2230), Tuple.Create<System.Object, System.Int32>(Href("~/CMS/Info/Mod/")
, 2230), false)
            
            #line 66 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create("", 2245), Tuple.Create<System.Object, System.Int32>(mod.ID
            
            #line default
            #line hidden
, 2245), false)
);

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"menu-icon fa fa-caret-right\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                        ");

            
            #line 68 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                   Write(mod);

            
            #line default
            #line hidden
WriteLiteral(" 管理\r\n                    </a>\r\n                </li>\r\n");

            
            #line 71 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                
            
            #line default
            #line hidden
            
            #line 71 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                 foreach (ICategory cat2 in mod.GetTopCategories())
                {
                    
            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
               Write(Html.Partial("_Left_Category", cat2));

            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                                         ;
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </li>\r\n");

            
            #line 77 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n<!-- /.nav-list -->\r\n");

        }
    }
}
#pragma warning restore 1591
