#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 2 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    using NewLife.Cube;
    
    #line 1 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    using NewLife.Model;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/_Left.cshtml")]
    public partial class _Areas_Admin_Views_Index__Left_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index__Left_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
  
    var user = ManageProvider.Provider.Current as IUser;

    var fact = ObjectContainer.Current.Resolve<IMenuFactory>();

    var Menus = fact.Root.Childs;
    if (user != null && user.Role != null)
    {
        Menus = fact.GetMySubMenus(fact.Root.ID);
    }

    // 如果顶级只有一层，并且至少有三级目录，则提升一级
    if (Menus.Count == 1 && Menus[0].Childs.All(m => m.Childs.Count > 0)) { Menus = Menus[0].Childs; }

    String[] icos = new String[] { "fa-tachometer", "fa-desktop", "fa-list", "fa-pencil-square-o", "fa-list-alt", "fa-calendar", "fa-picture-o", "fa-tag", "fa-file-o" };
    Int32 _idx = 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n<ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
     foreach (IMenu menu in Menus.Where(m => m.Visible))
    {
        if (_idx >= icos.Length) { _idx = 0; }

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(">\r\n                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 877), Tuple.Create("\"", 911)
, Tuple.Create(Tuple.Create("", 885), Tuple.Create("menu-icon", 885), true)
, Tuple.Create(Tuple.Create(" ", 894), Tuple.Create("fa", 895), true)
            
            #line 26 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create(" ", 897), Tuple.Create<System.Object, System.Int32>(icos[_idx++]
            
            #line default
            #line hidden
, 898), false)
);

WriteLiteral("></i>\r\n                <span");

WriteLiteral(" class=\"menu-text\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                   Write(menu.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n                <b");

WriteLiteral(" class=\"arrow fa fa-angle-down\"");

WriteLiteral("></b>\r\n            </a>\r\n\r\n            <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n\r\n            <ul");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                 foreach (IMenu menu2 in menu.Childs.Where(m => m.Visible))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

            
            #line 38 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                         if (menu2.Childs.Count > 0)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"menu-icon fa fa-caret-right\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                                ");

            
            #line 42 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                           Write(menu2.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </a>\r\n");

            
            #line 44 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1680), Tuple.Create("\"", 1710)
            
            #line 47 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create("", 1687), Tuple.Create<System.Object, System.Int32>(Url.Content(menu2.Url)
            
            #line default
            #line hidden
, 1687), false)
);

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"menu-icon fa fa-caret-right\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                                ");

            
            #line 49 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                           Write(menu2.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </a>\r\n");

            
            #line 51 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n                        <ul");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\r\n");

            
            #line 55 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                             foreach (IMenu menu3 in menu2.Childs.Where(m => m.Visible))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2210), Tuple.Create("\"", 2240)
            
            #line 58 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create("", 2217), Tuple.Create<System.Object, System.Int32>(Url.Content(menu3.Url)
            
            #line default
            #line hidden
, 2217), false)
);

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"menu-icon fa fa-caret-right\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                                        ");

            
            #line 60 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                   Write(menu3.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n\r\n                                   " +
" <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n                                </li>\r\n");

            
            #line 65 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </li>\r\n");

            
            #line 68 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </li>\r\n");

            
            #line 71 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n");

            
            #line 73 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    
            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
     foreach (var chn in Channel.FindAllWithCache().ToList().Where(e => e.Enable))
    {
        var provider = chn.Model.Provider;

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(">\r\n                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 2931), Tuple.Create("\"", 2965)
, Tuple.Create(Tuple.Create("", 2939), Tuple.Create("menu-icon", 2939), true)
, Tuple.Create(Tuple.Create(" ", 2948), Tuple.Create("fa", 2949), true)
            
            #line 78 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create(" ", 2951), Tuple.Create<System.Object, System.Int32>(icos[_idx++]
            
            #line default
            #line hidden
, 2952), false)
);

WriteLiteral("></i>\r\n                <span");

WriteLiteral(" class=\"menu-text\"");

WriteLiteral(">");

            
            #line 79 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                   Write(chn.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n                <b");

WriteLiteral(" class=\"arrow fa fa-angle-down\"");

WriteLiteral("></b>\r\n            </a>\r\n\r\n            <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n\r\n            <ul");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3224), Tuple.Create("\"", 3269)
, Tuple.Create(Tuple.Create("", 3231), Tuple.Create<System.Object, System.Int32>(Href("~/CMS_")
, 3231), false)
            
            #line 88 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create("", 3237), Tuple.Create<System.Object, System.Int32>(chn.ID
            
            #line default
            #line hidden
, 3237), false)
, Tuple.Create(Tuple.Create("", 3244), Tuple.Create("/", 3244), true)
            
            #line 88 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create("", 3245), Tuple.Create<System.Object, System.Int32>(chn.Model.Name
            
            #line default
            #line hidden
, 3245), false)
, Tuple.Create(Tuple.Create(" ", 3260), Tuple.Create("Category", 3261), true)
);

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"menu-icon fa fa-caret-right\"");

WriteLiteral("></i>\r\n                        分类管理\r\n                    </a>\r\n                </" +
"li>\r\n");

            
            #line 93 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                
            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                 foreach (IEntityCategory cat in provider.CategoryFactory.FindAllWithCache())
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"menu-icon fa fa-caret-right\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                            ");

            
            #line 98 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                       Write(cat.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n\r\n                        <b");

WriteLiteral(" class=\"arrow\"");

WriteLiteral("></b>\r\n                    </li>\r\n");

            
            #line 103 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </li>\r\n");

            
            #line 106 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n<!-- /.nav-list -->\r\n");

        }
    }
}
#pragma warning restore 1591
