#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.CMX;
    using NewLife.CMX.Web;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Product/Category.cshtml")]
    public partial class _Views_Product_Category_cshtml : System.Web.Mvc.WebViewPage<NewLife.CMX.IEntityCategory>
    {
        public _Views_Product_Category_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Product\Category.cshtml"
  
    var Channel = ViewBag.Channel as Channel;
    var Titles = ViewBag.Titles as IList<IEntityTitle>;
    var Pager = ViewBag.Pager as Pager;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"min-height: 600px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\Product\Category.cshtml"
   Write(Html.Partial("_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <h2");

WriteLiteral(" class=\"tith2\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\Product\Category.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h2>\r\n");

            
            #line 14 "..\..\Views\Product\Category.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Product\Category.cshtml"
      
        var childs = Model.Childs;
        if (childs.Count > 0)
        {
            foreach (IEntityCategory cat in childs)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"widget2 fixed\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"tit\"");

WriteLiteral(">\r\n                        <em>");

            
            #line 22 "..\..\Views\Product\Category.cshtml"
                       Write(cat.Name);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                        <small");

WriteLiteral(" style=\"float: right;\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 728), Tuple.Create("\"", 760)
            
            #line 24 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 735), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(cat)
            
            #line default
            #line hidden
, 735), false)
);

WriteLiteral(">更多 &gt;&gt;</a>\r\n                        </small>\r\n                    </h2>\r\n  " +
"                  <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"list_news_dl fixed\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Product\Category.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Product\Category.cshtml"
                             foreach (var title in cat.GetTitles())
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1116), Tuple.Create("\"", 1142)
            
            #line 32 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 1123), Tuple.Create<System.Object, System.Int32>(this.GetUrl(title)
            
            #line default
            #line hidden
, 1123), false)
);

WriteLiteral(">\r\n                                        <i></i>");

            
            #line 33 "..\..\Views\Product\Category.cshtml"
                                          Write(title.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n                                </li>" +
"\r\n");

            
            #line 36 "..\..\Views\Product\Category.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n                </div>" +
"\r\n");

            
            #line 40 "..\..\Views\Product\Category.cshtml"
            }
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <ul");

WriteLiteral(" class=\"list_news_dl fixed\"");

WriteLiteral(">\r\n");

            
            #line 45 "..\..\Views\Product\Category.cshtml"
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Product\Category.cshtml"
                 foreach (var item in Titles)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1616), Tuple.Create("\"", 1641)
            
            #line 48 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 1623), Tuple.Create<System.Object, System.Int32>(this.GetUrl(item)
            
            #line default
            #line hidden
, 1623), false)
);

WriteLiteral(">\r\n                            <i></i>");

            
            #line 49 "..\..\Views\Product\Category.cshtml"
                              Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </li>\r\n");

            
            #line 52 "..\..\Views\Product\Category.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

            
            #line 54 "..\..\Views\Product\Category.cshtml"
            if (Pager.PageCount > 1)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"cor01\"");

WriteLiteral(">页数：");

            
            #line 57 "..\..\Views\Product\Category.cshtml"
                                      Write(Pager.PageIndex);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 57 "..\..\Views\Product\Category.cshtml"
                                                       Write(Pager.PageCount);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    <a");

WriteLiteral(" class=\"first\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1998), Tuple.Create("\"", 2034)
            
            #line 58 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2005), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model)
            
            #line default
            #line hidden
, 2005), false)
);

WriteLiteral(" title=\"首页\"");

WriteLiteral(">首页</a>\r\n");

            
            #line 59 "..\..\Views\Product\Category.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Product\Category.cshtml"
                     if (Pager.PageIndex > 1)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"prev\"");

WriteLiteral(" title=\"上一页\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2176), Tuple.Create("\"", 2233)
            
            #line 61 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2183), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, Pager.PageIndex - 1)
            
            #line default
            #line hidden
, 2183), false)
);

WriteLiteral(">&lt;</a>\r\n");

            
            #line 62 "..\..\Views\Product\Category.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 63 "..\..\Views\Product\Category.cshtml"
                     for (int i = 1; i <= Pager.PageCount; i++)
                    {
                        if (i == Pager.PageIndex)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" class=\"on\"");

WriteLiteral(">");

            
            #line 67 "..\..\Views\Product\Category.cshtml"
                                     Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 68 "..\..\Views\Product\Category.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2598), Tuple.Create("\"", 2637)
            
            #line 71 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2605), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, i)
            
            #line default
            #line hidden
, 2605), false)
);

WriteLiteral(">");

            
            #line 71 "..\..\Views\Product\Category.cshtml"
                                                                  Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 72 "..\..\Views\Product\Category.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 74 "..\..\Views\Product\Category.cshtml"
                     if (Pager.PageIndex < Pager.PageCount)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"next\"");

WriteLiteral(" title=\"下一页\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2832), Tuple.Create("\"", 2889)
            
            #line 76 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2839), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, Pager.PageIndex + 1)
            
            #line default
            #line hidden
, 2839), false)
);

WriteLiteral(">&gt;</a>\r\n");

            
            #line 77 "..\..\Views\Product\Category.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"first\"");

WriteLiteral(" title=\"末页\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2971), Tuple.Create("\"", 3024)
            
            #line 78 "..\..\Views\Product\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2978), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, Pager.PageCount)
            
            #line default
            #line hidden
, 2978), false)
);

WriteLiteral(">末页</a>\r\n                </div>\r\n");

            
            #line 80 "..\..\Views\Product\Category.cshtml"
            }
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
