#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.CMX;
    using NewLife.CMX.Web;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Article/Category.cshtml")]
    public partial class _Views_Article_Category_cshtml : System.Web.Mvc.WebViewPage<NewLife.CMX.IEntityCategory>
    {
        public _Views_Article_Category_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Article\Category.cshtml"
  
    var Channel = ViewBag.Channel as Channel;
    var Titles = ViewBag.Titles as IList<IEntityTitle>;
    var Pager = ViewBag.Pager as Pager;

    var root = Model;
    while (root.Parent != null && root.Parent != root)
    {
        root = root.Parent as IEntityCategory;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"min-height: 600px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Article\Category.cshtml"
   Write(Html.Partial("../Article/_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <h2");

WriteLiteral(" class=\"tith2\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Article\Category.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h2>\r\n");

            
            #line 20 "..\..\Views\Article\Category.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Article\Category.cshtml"
      
        var childs = Model.Childs;
        if (childs.Count > 0)
        {
            foreach (IEntityCategory cat in childs)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"widget2 fixed\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"tit\"");

WriteLiteral(">\r\n                        <em>");

            
            #line 28 "..\..\Views\Article\Category.cshtml"
                       Write(cat.Name);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                        <small");

WriteLiteral(" style=\"float: right;\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 882), Tuple.Create("\"", 914)
            
            #line 30 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 889), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(cat)
            
            #line default
            #line hidden
, 889), false)
);

WriteLiteral(">更多 &gt;&gt;</a>\r\n                        </small>\r\n                    </h2>\r\n  " +
"                  <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"list_news_dl fixed\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Views\Article\Category.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Article\Category.cshtml"
                             foreach (var title in cat.GetTitles())
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1270), Tuple.Create("\"", 1296)
            
            #line 38 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 1277), Tuple.Create<System.Object, System.Int32>(this.GetUrl(title)
            
            #line default
            #line hidden
, 1277), false)
);

WriteLiteral(">\r\n                                        <i></i>");

            
            #line 39 "..\..\Views\Article\Category.cshtml"
                                          Write(title.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n                                </li>" +
"\r\n");

            
            #line 42 "..\..\Views\Article\Category.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n                </div>" +
"\r\n");

            
            #line 46 "..\..\Views\Article\Category.cshtml"
            }
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <ul");

WriteLiteral(" class=\"list_news_dl fixed\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Article\Category.cshtml"
                
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Article\Category.cshtml"
                 foreach (var item in Titles)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1770), Tuple.Create("\"", 1795)
            
            #line 54 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 1777), Tuple.Create<System.Object, System.Int32>(this.GetUrl(item)
            
            #line default
            #line hidden
, 1777), false)
);

WriteLiteral(">\r\n                            <i></i>");

            
            #line 55 "..\..\Views\Article\Category.cshtml"
                              Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </a>\r\n                    </li>\r\n");

            
            #line 58 "..\..\Views\Article\Category.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");

            
            #line 60 "..\..\Views\Article\Category.cshtml"
            if (Pager.PageCount > 1)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"cor01\"");

WriteLiteral(">页数：");

            
            #line 63 "..\..\Views\Article\Category.cshtml"
                                      Write(Pager.PageIndex);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 63 "..\..\Views\Article\Category.cshtml"
                                                       Write(Pager.PageCount);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    <a");

WriteLiteral(" class=\"first\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2152), Tuple.Create("\"", 2188)
            
            #line 64 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2159), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model)
            
            #line default
            #line hidden
, 2159), false)
);

WriteLiteral(" title=\"首页\"");

WriteLiteral(">首页</a>\r\n");

            
            #line 65 "..\..\Views\Article\Category.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Article\Category.cshtml"
                     if (Pager.PageIndex > 1)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"prev\"");

WriteLiteral(" title=\"上一页\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2330), Tuple.Create("\"", 2387)
            
            #line 67 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2337), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, Pager.PageIndex - 1)
            
            #line default
            #line hidden
, 2337), false)
);

WriteLiteral(">&lt;</a>\r\n");

            
            #line 68 "..\..\Views\Article\Category.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 69 "..\..\Views\Article\Category.cshtml"
                     for (int i = 1; i <= Pager.PageCount; i++)
                    {
                        if (i == Pager.PageIndex)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" class=\"on\"");

WriteLiteral(">");

            
            #line 73 "..\..\Views\Article\Category.cshtml"
                                     Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 74 "..\..\Views\Article\Category.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2752), Tuple.Create("\"", 2791)
            
            #line 77 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2759), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, i)
            
            #line default
            #line hidden
, 2759), false)
);

WriteLiteral(">");

            
            #line 77 "..\..\Views\Article\Category.cshtml"
                                                                  Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 78 "..\..\Views\Article\Category.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 80 "..\..\Views\Article\Category.cshtml"
                     if (Pager.PageIndex < Pager.PageCount)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"next\"");

WriteLiteral(" title=\"下一页\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2986), Tuple.Create("\"", 3043)
            
            #line 82 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 2993), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, Pager.PageIndex + 1)
            
            #line default
            #line hidden
, 2993), false)
);

WriteLiteral(">&gt;</a>\r\n");

            
            #line 83 "..\..\Views\Article\Category.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"first\"");

WriteLiteral(" title=\"末页\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3125), Tuple.Create("\"", 3178)
            
            #line 84 "..\..\Views\Article\Category.cshtml"
, Tuple.Create(Tuple.Create("", 3132), Tuple.Create<System.Object, System.Int32>(this.GetCategoryUrl(Model, Pager.PageCount)
            
            #line default
            #line hidden
, 3132), false)
);

WriteLiteral(">末页</a>\r\n                </div>\r\n");

            
            #line 86 "..\..\Views\Article\Category.cshtml"
            }
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
