#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 1 "..\..\Areas\CMS\Views\Text\Form.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 4 "..\..\Areas\CMS\Views\Text\Form.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\CMS\Views\Text\Form.cshtml"
    using NewLife.CMX.Web;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Areas\CMS\Views\Text\Form.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\CMS\Views\Text\Form.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Text/Form.cshtml")]
    public partial class _Areas_CMS_Views_Text_Form_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_CMS_Views_Text_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Areas\CMS\Views\Text\Form.cshtml"
  
    var fact = EntityFactory.CreateOperate(ViewData.ModelMetadata.ModelType);
    var fields = ViewBag.Fields as List<FieldItem>;
    var isNew = (Model as IEntity).IsNullKey;
    var entity = Model as IEntity;
    var text = Model as IText;
    var inf = (Model as IInfoExtend).Info;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Areas\CMS\Views\Text\Form.cshtml"
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\CMS\Views\Text\Form.cshtml"
         if (ViewBag.StatusMessage != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"alert alert-success alert-dismissible text-center\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                <strong>");

            
            #line 20 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n            </div>\r\n");

            
            #line 22 "..\..\Areas\CMS\Views\Text\Form.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 23 "..\..\Areas\CMS\Views\Text\Form.cshtml"
         using (Html.BeginForm((isNew ? "Add" : "Edit"), null, new { id = Model[fact.Unique.Name] }))
        {
            
            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\CMS\Views\Text\Form.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\CMS\Views\Text\Form.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">标题</label>\r\n                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Areas\CMS\Views\Text\Form.cshtml"
               Write(Html.ForEditor("Title", inf));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    &nbsp;\r\n");

            
            #line 32 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                     if (!isNew)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1355), Tuple.Create("\"", 1379)
            
            #line 34 "..\..\Areas\CMS\Views\Text\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1362), Tuple.Create<System.Object, System.Int32>(this.GetUrl(inf)
            
            #line default
            #line hidden
, 1362), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                            预览\r\n                        </a>\r\n");

            
            #line 37 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">分类</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

            
            #line 43 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                      
            var data = new SelectList(Category.Root.AllChilds, "ID", "TreeNodeText", inf.CategoryID);
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Areas\CMS\Views\Text\Form.cshtml"
               Write(Html.DropDownList("CategoryID", data, new { @class = "multiselect" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">访问量</label>\r\n                    <span>");

            
            #line 50 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                     Write(inf.Views);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">版本</label>\r\n                    <span>");

            
            #line 52 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                     Write(inf.Version);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">内容</label>\r\n                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2408), Tuple.Create("\"", 2449)
, Tuple.Create(Tuple.Create("", 2414), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.config.js")
, 2414), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2489), Tuple.Create("\"", 2531)
, Tuple.Create(Tuple.Create("", 2495), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.all.min.js")
, 2495), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2571), Tuple.Create("\"", 2614)
, Tuple.Create(Tuple.Create("", 2577), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/lang/zh-cn/zh-cn.js")
, 2577), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteLiteral(" id=\"ContentText\"");

WriteLiteral(" name=\"ContentText\"");

WriteLiteral(" type=\"text/plain\"");

WriteLiteral(" style=\"width:800px;height:400px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 62 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                   Write(Html.Raw(inf.ContentText));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </script>\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                            //实例化编辑器
                            //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例
                            var ue = UE.getEditor('ContentText');
                    </script>
                </div>
            </div>
");

            
            #line 71 "..\..\Areas\CMS\Views\Text\Form.cshtml"
            
            
            #line default
            #line hidden
            
            #line 71 "..\..\Areas\CMS\Views\Text\Form.cshtml"
       Write(Html.Partial("_UserTime", Model as IEntity));

            
            #line default
            #line hidden
            
            #line 71 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                                                        
            
            
            #line default
            #line hidden
            
            #line 72 "..\..\Areas\CMS\Views\Text\Form.cshtml"
       Write(Html.Partial("_Form_Action", isNew));

            
            #line default
            #line hidden
            
            #line 72 "..\..\Areas\CMS\Views\Text\Form.cshtml"
                                                
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
