#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.CMX;
    using NewLife.CMX.Web;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Header.cshtml")]
    public partial class _Views_Shared__Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Header_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Header.cshtml"
  
    var header = Nav.Root.FindByPath("头部") ?? Nav.Root;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"float: left;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(" data-title=\"logo\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 194), Tuple.Create("\"", 225)
, Tuple.Create(Tuple.Create("", 200), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/logo.png")
, 200), false)
);

WriteLiteral(" alt=\"网站Logo\"");

WriteLiteral(" /></a>\r\n        </div>\r\n        <nav");

WriteLiteral(" class=\"navbar\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Shared\_Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Shared\_Header.cshtml"
                 foreach (var nav in header.Childs)
                {
                    if (nav.Childs.Count == 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 526), Tuple.Create("\"", 541)
            
            #line 15 "..\..\Views\Shared\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 533), Tuple.Create<System.Object, System.Int32>(nav.Url
            
            #line default
            #line hidden
, 533), false)
);

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Shared\_Header.cshtml"
                                                                             Write(nav.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 16 "..\..\Views\Shared\_Header.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\Shared\_Header.cshtml"
                                                                                                                      Write(nav.Name);

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></a>\r\n                            <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Shared\_Header.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\_Header.cshtml"
                                 foreach (var item in nav.Childs)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1094), Tuple.Create("\"", 1110)
            
            #line 24 "..\..\Views\Shared\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 1101), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 1101), false)
);

WriteLiteral(" class=\"\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Shared\_Header.cshtml"
                                                                Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 25 "..\..\Views\Shared\_Header.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </li>\r\n");

            
            #line 28 "..\..\Views\Shared\_Header.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </nav>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
