#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.CMX;
    using NewLife.CMX.Web;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Header.cshtml")]
    public partial class _Views_Shared__Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Header_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Header.cshtml"
  
    var header = Nav.Root.FindByPath("头部") ?? Nav.Root;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"top\"");

WriteLiteral(" data-s-dt=\"content\"");

WriteLiteral(" data-s-n=\"head\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"logo\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(" data-title=\"logo\"");

WriteLiteral("><img");

WriteLiteral(" src=\"/images/index/logo.png\"");

WriteLiteral(" data-retina=\"true\"");

WriteLiteral(" height=\"30\"");

WriteLiteral(" alt=\"网站Logo\"");

WriteLiteral(" /></a>\r\n    </div>\r\n    <nav");

WriteLiteral(" id=\"top-nav\"");

WriteLiteral(" class=\"hidden-phone\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" id=\"top-nav-menu\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\Shared\_Header.cshtml"
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\_Header.cshtml"
             foreach (var nav in header.Childs)
            {
                if (nav.Childs.Count == 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 503), Tuple.Create("\"", 518)
            
            #line 14 "..\..\Views\Shared\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 510), Tuple.Create<System.Object, System.Int32>(nav.Url
            
            #line default
            #line hidden
, 510), false)
);

WriteLiteral(" class=\"current\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Shared\_Header.cshtml"
                                                      Write(nav.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 15 "..\..\Views\Shared\_Header.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"has-submenu\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 688), Tuple.Create("\"", 703)
            
            #line 19 "..\..\Views\Shared\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 695), Tuple.Create<System.Object, System.Int32>(nav.Url
            
            #line default
            #line hidden
, 695), false)
);

WriteLiteral(" class=\"current\"");

WriteLiteral(">");

            
            #line 19 "..\..\Views\Shared\_Header.cshtml"
                                                      Write(nav.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        <ul");

WriteLiteral(" class=\"last\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Shared\_Header.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\_Header.cshtml"
                             foreach (var item in nav.Childs)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 911), Tuple.Create("\"", 927)
            
            #line 23 "..\..\Views\Shared\_Header.cshtml"
, Tuple.Create(Tuple.Create("", 918), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 918), false)
);

WriteLiteral(" class=\"current\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Shared\_Header.cshtml"
                                                                   Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 24 "..\..\Views\Shared\_Header.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </li>\r\n");

            
            #line 27 "..\..\Views\Shared\_Header.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </nav>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
