#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 1 "..\..\Areas\CMS\Views\Product\Form.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 4 "..\..\Areas\CMS\Views\Product\Form.cshtml"
    using NewLife.CMX;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Areas\CMS\Views\Product\Form.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\CMS\Views\Product\Form.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CMS/Views/Product/Form.cshtml")]
    public partial class _Areas_CMS_Views_Product_Form_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_CMS_Views_Product_Form_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Areas\CMS\Views\Product\Form.cshtml"
  
    var fact = EntityFactory.CreateOperate(ViewData.ModelMetadata.ModelType);
    var fields = ViewBag.Fields as List<FieldItem>;
    var isNew = (Model as IEntity).IsNullKey;
    var entity = Model as IEntity;
    var product = Model as IProduct;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Areas\CMS\Views\Product\Form.cshtml"
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\CMS\Views\Product\Form.cshtml"
         if (ViewBag.StatusMessage != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"alert alert-success alert-dismissible text-center\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                <strong>");

            
            #line 18 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n            </div>\r\n");

            
            #line 20 "..\..\Areas\CMS\Views\Product\Form.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 21 "..\..\Areas\CMS\Views\Product\Form.cshtml"
         using (Html.BeginForm((isNew ? "Add" : "Edit"), null, new { id = Model[fact.Unique.Name] }))
        {
            
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\CMS\Views\Product\Form.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\CMS\Views\Product\Form.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">标题</label>\r\n                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Areas\CMS\Views\Product\Form.cshtml"
               Write(Html.ForEditor(Product._.Title, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                  var item = Product._.CategoryID;
            
            #line default
            #line hidden
WriteLiteral("\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">");

            
            #line 33 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                                                 Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Areas\CMS\Views\Product\Form.cshtml"
               Write(Html.DropDownList(item.Name, ProductCategory.FindAllWithCache().ToList().Select(r => new SelectListItem { Text = r.Name, Value = r.ID + "" })));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 37 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                   item = Product._.Views;
            
            #line default
            #line hidden
WriteLiteral("\r\n                <label");

WriteLiteral(" class=\"control-label col-md-1\"");

WriteLiteral(">");

            
            #line 38 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                                                 Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Areas\CMS\Views\Product\Form.cshtml"
               Write(Html.ForEditor(item, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <label");

WriteLiteral(" class=\"control-label col-md-1\"");

WriteLiteral(">版本</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                    <span>");

            
            #line 44 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                     Write(product.Version);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">价格</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 50 "..\..\Areas\CMS\Views\Product\Form.cshtml"
               Write(Html.ForEditor(Product._.Price, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <label");

WriteLiteral(" class=\"control-label col-md-1\"");

WriteLiteral(">图片</label>\r\n                <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Areas\CMS\Views\Product\Form.cshtml"
               Write(Html.ForEditor(Product._.PhotoPath, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">内容</label>\r\n                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2696), Tuple.Create("\"", 2737)
, Tuple.Create(Tuple.Create("", 2702), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.config.js")
, 2702), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2777), Tuple.Create("\"", 2819)
, Tuple.Create(Tuple.Create("", 2783), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/ueditor.all.min.js")
, 2783), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2859), Tuple.Create("\"", 2902)
, Tuple.Create(Tuple.Create("", 2865), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ueditor/lang/zh-cn/zh-cn.js")
, 2865), false)
);

WriteLiteral("></script>\r\n                    <script");

WriteLiteral(" id=\"ContentText\"");

WriteLiteral(" name=\"ContentText\"");

WriteLiteral(" type=\"text/plain\"");

WriteLiteral(" style=\"width:500px;height:500px;\"");

WriteLiteral(">\r\n                    </script>\r\n                    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                            //实例化编辑器
                            //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例
                            var ue = UE.getEditor('ContentText');
                    </script>
                </div>
            </div>
");

            
            #line 72 "..\..\Areas\CMS\Views\Product\Form.cshtml"
            
            
            #line default
            #line hidden
            
            #line 72 "..\..\Areas\CMS\Views\Product\Form.cshtml"
       Write(Html.Partial("_UserTime", Model as IEntity));

            
            #line default
            #line hidden
            
            #line 72 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                                                        
            
            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\CMS\Views\Product\Form.cshtml"
       Write(Html.Partial("_Form_Action", isNew));

            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\CMS\Views\Product\Form.cshtml"
                                                
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
